import io
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class ReportService:
    def generate_html_doc(self, analysis_data: Dict[str, Any], submission_title: str) -> io.BytesIO:
        """
        Generate an HTML report designed to be opened as a .doc file.
        Returns a BytesIO object containing the content.
        """
        try:
            html = f"""
            <html>
            <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
                h1 {{ color: #2c3e50; text-align: center; }}
                h2 {{ color: #34495e; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
                .stats-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                .stats-table th, .stats-table td {{ border: 1px solid #ddd; padding: 12px; text-align: center; }}
                .stats-table th {{ background-color: #f8f9fa; }}
                .score-red {{ color: #c0392b; }}
                .score-green {{ color: #27ae60; }}
                .violation {{ margin-left: 20px; color: #555; }}
                .critical {{ color: #c0392b; font-weight: bold; }}
                .high {{ color: #d35400; font-weight: bold; }}
                .medium {{ color: #f39c12; }}
                .low {{ color: #2980b9; }}
                .footer {{ margin-top: 50px; font-size: 0.8em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            </style>
            </head>
            <body>
                <h1>Deep Compliance Analysis Report</h1>
                <p><strong>Document:</strong> {submission_title}</p>
                <p><strong>Analysis Status:</strong> {analysis_data.get('status', 'Completed').title()}</p>
                
                <h2>Executive Summary</h2>
                <table class="stats-table">
                    <tr>
                        <th>Total Lines</th>
                        <th>Average Score</th>
                        <th>Min Score</th>
                        <th>Max Score</th>
                    </tr>
                    <tr>
                        <td>{analysis_data.get('total_lines', 0)}</td>
                        <td>{analysis_data.get('average_score', 0):.2f}</td>
                        <td>{analysis_data.get('min_score', 0):.2f}</td>
                        <td>{analysis_data.get('max_score', 0):.2f}</td>
                    </tr>
                </table>
                
                <h3>Configuration Parameters</h3>
                <ul>
            """
            
            config = analysis_data.get('severity_config', {})
            for level, weight in config.items():
                html += f"<li><strong>{level.title()}:</strong> {weight}x</li>"
                
            html += """
                </ul>
                
                <h2>Detailed Line-by-Line Analysis</h2>
            """
            
            lines = analysis_data.get('lines', [])
            for line in lines:
                content = line.get('line_content', '').strip()
                if not content: continue
                
                score = line.get('line_score', 100)
                impacts = line.get('rule_impacts', [])
                
                score_class = "score-red" if score < 100 else "score-green"
                
                html += f"""
                <div style="margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 10px;">
                    <p><strong>Line {line.get('line_number')}:</strong> {content}</p>
                """
                
                if impacts or score < 100:
                    html += f'<p style="margin-left: 20px;"><strong>Score: <span class="{score_class}">{score:.2f}/100</span></strong></p>'
                
                if impacts:
                    html += "<ul>"
                    for impact in impacts:
                        sev = impact.get('severity', 'low').lower()
                        deduction = impact.get('weighted_deduction', 0)
                        html += f"""
                        <li class="violation">
                            <span class="{sev}">[{sev.upper()}]</span> -{deduction:.1f} pts: {impact.get('violation_reason')}
                        </li>
                        """
                    html += "</ul>"
                
                html += "</div>"
                
            html += """
                <div class="footer">
                    Generated by Compliance Agent Deep Research
                </div>
            </body>
            </html>
            """
            
            return io.BytesIO(html.encode('utf-8'))
            
        except Exception as e:
            logger.error(f"Error building HTML DOC: {e}")
            raise RuntimeError(f"Error building report: {e}")

report_service = ReportService()
